# $FreeBSD$
#

    COMMENT = Wayland libraries, compositors and clients

    SUBDIR += libepoll-shim
    SUBDIR += libgudev
    SUBDIR += libinput
    SUBDIR += libudev-devd
    SUBDIR += libwacom
    SUBDIR += sway
    SUBDIR += wayland
    SUBDIR += wayland-protocols
    SUBDIR += weston
    SUBDIR += wlc

.include <bsd.port.subdir.mk>
