# $FreeBSD$

PORTNAME=	x11perf
PORTVERSION=	1.6.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 server performance test program

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xmuu xrender xft xext

.include <bsd.port.mk>
